//------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated from a template.
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;

    // 1. Thêm thư viện này để dùng các lệnh [Required], [StringLength]
    using System.ComponentModel.DataAnnotations;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Products = new HashSet<Product>();
        }

        public int CategoryID { get; set; }

        // --- BẮT ĐẦU SỬA Ở ĐÂY ---
        [Display(Name = "Tên danh mục")]
        [Required(ErrorMessage = "Vui lòng nhập tên danh mục!")]
        [StringLength(30, ErrorMessage = "Tên danh mục không được quá 30 ký tự!")] // Chặn nhập dài
        public string CategoryName { get; set; }
        // --- KẾT THÚC SỬA ---

        [Display(Name = "Ảnh minh họa")]
        public string ImageUrl { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}   